#!/bin/bash
##########################################################################
# This file is centrally managed, any manual changes will be OVERWRITTEN #
##########################################################################
# chkconfig: 345 85 15
# description: Startup script for btsync daemon
#
# processname: btsync
# pidfile: /var/run/btsync/btsync.pid
# config: /etc/btsync.conf
#

### BEGIN INIT INFO
# Provides: btsync
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start up the btsync file syncing daemon
# Description: btsync
# This service starts up the btsync daemon.
### END INIT INFO

BIN='/usr/bin/btsync'
CONF='/etc/btsync.conf'
PID='/var/run/btsync/btsync.pid'
PIDMATCH=true
SERVICE=$(basename $0)

test $(id -u) -ne 0 && echo "This is for root." >&2 && exit 1

main(){
	case $1 in
	  start)
	    if begin
	    then
	      echo "$SERVICE successfully started"
	      exit 0
	    else
	      echo "Error starting $SERVICE." >&2
	      exit 1
	    fi
	  ;;
	  stop)
	    if end
	    then
	      echo "$SERVICE successfully stopped"
	      exit 0
	    else
	      echo "Error stopping $SERVICE" >&2
	      exit 1
	    fi
	  ;;
	  status)
	    query
	    exit $?
	  ;;
	  *)
	    printUsage
	    exit 1
	  ;;
	esac
}

running(){
	test ! -f $PID && return 1
  listen=$(netstat -tnlp | grep btsync | awk '{print $NF}' | cut -d'/' -f1 | head -1)
	last=$(cat $PID)
	test -z $listen && return 1
	if [[ $listen -ne $last ]]
	then
	  echo "Warning: PID of listening instance does not match PID in $PID" >&2
	  PIDMATCH=false
	  return 0
	else
	  return 0
	fi
}

begin(){
	if running
	then
	  echo "$SERVICE is already running." >&2
	  return 1
	else
	  $BIN --config $CONF
	fi
}

end(){
	if running
	then
	  if ! $PIDMATCH
	  then
	    echo "Error: Failed to stop $SERVICE: PID in $PID does not match PID of listening instance" >&2
	    return 1
	  fi
	  kill -15 $(cat $PID)
	  xstat=$?
	  rm $PID
	  return $xstat
	else
	  echo "$SERVICE is not running."
	  return 1
	fi
}

query(){
	if running
	then
	  echo "$SERVICE is running"
	  return 0
	else
	  echo "$SERVICE is stopped"
	  return 0
	fi
}

printUsage(){
	echo "Usage: $0 [start|stop|status]"
}

main $*
